[package]
name = "rdms"
version = "0.0.1"
authors = ["prataprc <prataprc@gmail.com>"]
description = "Composable storage for key,value index"
documentation = "https://docs.rs/rdms"
homepage = "https://github.com/bnclabs/rdms"
repository = "https://github.com/bnclabs/rdms"
keywords = ["storage", "mvcc", "llrb", "btree", "lsm"]
categories = ["data-structures", "database"]
license = "AGPL-3.0"
exclude = ["template/**", "docs/**"]
readme = "README.md"
edition = "2018"

[lib]
name = "rdms"
path = "src/lib.rs"

[badges]
maintenance = { status = "actively-developed" }
travis-ci = { repository = "bnclabs/rdms" }

[dependencies]
lazy_static = "1.2.0"
jsondata = "0.6.2"
log = "0.4.8"
fs2 = "0.4.3"
memmap = "0.7.0"
croaring = "0.4.1"

[dev-dependencies]
rand = "0.6.4"
