[package]
name = "rdms"
version = "0.0.1"
authors = ["prataprc <prataprc@gmail.com>"]
description = "Composable storage for key,value index"
documentation = "https://docs.rs/rdms"
homepage = "https://github.com/bnclabs/rdms"
repository = "https://github.com/bnclabs/rdms"
keywords = ["storage", "mvcc", "llrb", "btree", "lsm"]
categories = ["data-structures", "database"]
license = "AGPL-3.0"
exclude = ["template/**", "docs/**"]
readme = "README.md"
edition = "2018"

[lib]
name = "rdms"
path = "src/lib.rs"

[badges]
maintenance = { status = "actively-developed" }
travis-ci = { repository = "bnclabs/rdms" }

[dependencies]
structopt = { version = "0.2", default-features = false }
lazy_static = "1.2.0"
jsondata = "0.6.2"
rand = "0.6.4"

[target.'cfg(unix)'.dependencies]
libc = "0.2.30"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["handleapi", "processthreadsapi", "winerror", "fileapi", "winbase", "std"] }

[dev-dependencies]
rand = "0.6.4"

